custom:
  writeEnvVars: ${file(./.env.yml)}
service: ${self:custom.writeEnvVars.SERVICE_NAME}
#service: trap

provider:
  name: aws
  runtime: python2.7
  stage: ${self:custom.writeEnvVars.STAGE}
  region: ${self:custom.writeEnvVars.REGION}
  memorySize: 128
  deploymentBucket: ${self:custom.writeEnvVars.DEPLOYMENT_BUCKET}
  #profile: dev-account
  ## Lambda function permissions
  ## S3 permissions are needed when you want to load the config from S3, or store the logs to S3
  ## You can set permission policy statements:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:Get*
        - s3:List*
      Resource: "*"
  ## OR you can overwrite the default IAM role and use an existing one:
  #role: arn:aws:iam::YourAccountNumber:role/YourIamRole

functions:
  honeylambda:
    handler: handler.honeylambda
    ## Function level environment variable
    environment:
      ## Load configuration from 'local' file or 's3' bucket
      configFile: s3
      ## Specify the S3 bucket to load the config file from
      ## Make sure your bucket is in the same region as Lambda function
      s3Bucket: ${self:custom.writeEnvVars.CONFIG_BUCKET}
      s3Key: notifications-config.json
    events:
      - http:
          path: v1/get-pass
          method: get

